### PR TITLE
Add webcomponents polyfill to increase browser support.

### PR DESCRIPTION
**Pull request by whmountains**

### CODE REVIEW

**Comment by whmountains** [comment]
Great, thanks!

**Comment by richiksc** [comment]
Was this tested? Just tested in Firefox 47.0, does not work.

**Comment by richiksc** [comment]
I checked the console in FF. Webcomponents js is imported twice which
causes issues.

**Comment by whmountains** [comment]
Strange.  In FF nightly the first import fails with "file not found".

**Pull request merged**
